version: "3.8"

services:
  web:
    image: docmd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/convert"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads:
    driver: local
